services:
   - type: web
     name: filmhub-help-chatbot-api
     runtime: docker
     plan: free
     healthCheckPath: /
     envVars:
        - key: OPENAI_API_KEY
          sync: false
        - key: PORT
          value: 10000
   - type: web
     name: filmhub-help-chatbot-client
     runtime: docker
     dockerfilePath: ./Dockerfile.client
     plan: free
