services:
   - type: web
     name: filmhub-help-chatbot-api
     runtime: docker
     plan: free
     healthCheckPath: /
     envVars:
        - key: OPENAI_API_KEY
          sync: false
        - key: PORT
          value: 10000
   - type: web
     name: filmhub-help-chatbot-client
     runtime: static
     buildCommand: curl -fsSL https://bun.sh/install | bash && export BUN_INSTALL="$HOME/.bun" && export PATH="$BUN_INSTALL/bin:$PATH" && bun install && bun --cwd packages/client run build
     staticPublishPath: packages/client/dist
     routes:
        - type: rewrite
          source: /api/*
          destination: https://filmhub-help-chatbot-api.onrender.com/api/*
        - type: rewrite
          source: /*
          destination: /index.html
